# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Wed Nov 20 00:47:23 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(613, 604)
        MainWindow.setMaximumSize(QtCore.QSize(1443, 921))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graficoplot = Qwt5.QwtPlot(self.centralwidget)
        self.graficoplot.setGeometry(QtCore.QRect(341, 21, 253, 231))
        self.graficoplot.setProperty("propertiesDocument", _fromUtf8(""))
        self.graficoplot.setObjectName(_fromUtf8("graficoplot"))
        self.tecla1 = QtGui.QPushButton(self.centralwidget)
        self.tecla1.setGeometry(QtCore.QRect(22, 279, 80, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla1.sizePolicy().hasHeightForWidth())
        self.tecla1.setSizePolicy(sizePolicy)
        self.tecla1.setMinimumSize(QtCore.QSize(80, 300))
        self.tecla1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 245);"))
        self.tecla1.setText(_fromUtf8(""))
        self.tecla1.setCheckable(False)
        self.tecla1.setAutoDefault(False)
        self.tecla1.setDefault(False)
        self.tecla1.setFlat(False)
        self.tecla1.setObjectName(_fromUtf8("tecla1"))
        self.tecla2 = QtGui.QPushButton(self.centralwidget)
        self.tecla2.setGeometry(QtCore.QRect(103, 279, 80, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla2.sizePolicy().hasHeightForWidth())
        self.tecla2.setSizePolicy(sizePolicy)
        self.tecla2.setMinimumSize(QtCore.QSize(80, 300))
        self.tecla2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 245);"))
        self.tecla2.setText(_fromUtf8(""))
        self.tecla2.setCheckable(False)
        self.tecla2.setAutoDefault(False)
        self.tecla2.setDefault(False)
        self.tecla2.setFlat(False)
        self.tecla2.setObjectName(_fromUtf8("tecla2"))
        self.tecla3 = QtGui.QPushButton(self.centralwidget)
        self.tecla3.setGeometry(QtCore.QRect(184, 279, 80, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla3.sizePolicy().hasHeightForWidth())
        self.tecla3.setSizePolicy(sizePolicy)
        self.tecla3.setMinimumSize(QtCore.QSize(80, 300))
        self.tecla3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 245);"))
        self.tecla3.setText(_fromUtf8(""))
        self.tecla3.setCheckable(False)
        self.tecla3.setAutoDefault(False)
        self.tecla3.setDefault(False)
        self.tecla3.setFlat(False)
        self.tecla3.setObjectName(_fromUtf8("tecla3"))
        self.tecla6 = QtGui.QPushButton(self.centralwidget)
        self.tecla6.setGeometry(QtCore.QRect(427, 279, 80, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla6.sizePolicy().hasHeightForWidth())
        self.tecla6.setSizePolicy(sizePolicy)
        self.tecla6.setMinimumSize(QtCore.QSize(80, 300))
        self.tecla6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 245);"))
        self.tecla6.setText(_fromUtf8(""))
        self.tecla6.setCheckable(False)
        self.tecla6.setAutoDefault(False)
        self.tecla6.setDefault(False)
        self.tecla6.setFlat(False)
        self.tecla6.setObjectName(_fromUtf8("tecla6"))
        self.tecla4 = QtGui.QPushButton(self.centralwidget)
        self.tecla4.setGeometry(QtCore.QRect(265, 279, 80, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla4.sizePolicy().hasHeightForWidth())
        self.tecla4.setSizePolicy(sizePolicy)
        self.tecla4.setMinimumSize(QtCore.QSize(80, 300))
        self.tecla4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 245);"))
        self.tecla4.setText(_fromUtf8(""))
        self.tecla4.setCheckable(False)
        self.tecla4.setAutoDefault(False)
        self.tecla4.setDefault(False)
        self.tecla4.setFlat(False)
        self.tecla4.setObjectName(_fromUtf8("tecla4"))
        self.tecla7 = QtGui.QPushButton(self.centralwidget)
        self.tecla7.setGeometry(QtCore.QRect(508, 279, 80, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla7.sizePolicy().hasHeightForWidth())
        self.tecla7.setSizePolicy(sizePolicy)
        self.tecla7.setMinimumSize(QtCore.QSize(80, 300))
        self.tecla7.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 245);"))
        self.tecla7.setText(_fromUtf8(""))
        self.tecla7.setCheckable(False)
        self.tecla7.setAutoDefault(False)
        self.tecla7.setDefault(False)
        self.tecla7.setFlat(False)
        self.tecla7.setObjectName(_fromUtf8("tecla7"))
        self.tecla5 = QtGui.QPushButton(self.centralwidget)
        self.tecla5.setGeometry(QtCore.QRect(346, 279, 80, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla5.sizePolicy().hasHeightForWidth())
        self.tecla5.setSizePolicy(sizePolicy)
        self.tecla5.setMinimumSize(QtCore.QSize(80, 300))
        self.tecla5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 245);"))
        self.tecla5.setText(_fromUtf8(""))
        self.tecla5.setCheckable(False)
        self.tecla5.setAutoDefault(False)
        self.tecla5.setDefault(False)
        self.tecla5.setFlat(False)
        self.tecla5.setObjectName(_fromUtf8("tecla5"))
        self.tecla8 = QtGui.QPushButton(self.centralwidget)
        self.tecla8.setGeometry(QtCore.QRect(80, 270, 40, 170))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla8.sizePolicy().hasHeightForWidth())
        self.tecla8.setSizePolicy(sizePolicy)
        self.tecla8.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
""))
        self.tecla8.setText(_fromUtf8(""))
        self.tecla8.setAutoDefault(False)
        self.tecla8.setFlat(False)
        self.tecla8.setObjectName(_fromUtf8("tecla8"))
        self.tecla9 = QtGui.QPushButton(self.centralwidget)
        self.tecla9.setGeometry(QtCore.QRect(160, 270, 40, 170))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla9.sizePolicy().hasHeightForWidth())
        self.tecla9.setSizePolicy(sizePolicy)
        self.tecla9.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
""))
        self.tecla9.setText(_fromUtf8(""))
        self.tecla9.setAutoDefault(False)
        self.tecla9.setFlat(False)
        self.tecla9.setObjectName(_fromUtf8("tecla9"))
        self.tecla9_2 = QtGui.QPushButton(self.centralwidget)
        self.tecla9_2.setGeometry(QtCore.QRect(330, 270, 40, 170))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla9_2.sizePolicy().hasHeightForWidth())
        self.tecla9_2.setSizePolicy(sizePolicy)
        self.tecla9_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
""))
        self.tecla9_2.setText(_fromUtf8(""))
        self.tecla9_2.setAutoDefault(False)
        self.tecla9_2.setFlat(False)
        self.tecla9_2.setObjectName(_fromUtf8("tecla9_2"))
        self.tecla9_3 = QtGui.QPushButton(self.centralwidget)
        self.tecla9_3.setGeometry(QtCore.QRect(410, 270, 40, 170))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla9_3.sizePolicy().hasHeightForWidth())
        self.tecla9_3.setSizePolicy(sizePolicy)
        self.tecla9_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
""))
        self.tecla9_3.setText(_fromUtf8(""))
        self.tecla9_3.setAutoDefault(False)
        self.tecla9_3.setFlat(False)
        self.tecla9_3.setObjectName(_fromUtf8("tecla9_3"))
        self.tecla9_4 = QtGui.QPushButton(self.centralwidget)
        self.tecla9_4.setGeometry(QtCore.QRect(490, 270, 40, 170))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tecla9_4.sizePolicy().hasHeightForWidth())
        self.tecla9_4.setSizePolicy(sizePolicy)
        self.tecla9_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
""))
        self.tecla9_4.setText(_fromUtf8(""))
        self.tecla9_4.setAutoDefault(False)
        self.tecla9_4.setFlat(False)
        self.tecla9_4.setObjectName(_fromUtf8("tecla9_4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 21, 311, 101))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lcdFrequencia = QtGui.QLCDNumber(self.widget)
        self.lcdFrequencia.setObjectName(_fromUtf8("lcdFrequencia"))
        self.verticalLayout.addWidget(self.lcdFrequencia)
        self.frequencia = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.frequencia.setFont(font)
        self.frequencia.setAlignment(QtCore.Qt.AlignCenter)
        self.frequencia.setObjectName(_fromUtf8("frequencia"))
        self.verticalLayout.addWidget(self.frequencia)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(21, 131, 314, 121))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dial_3 = QtGui.QDial(self.widget1)
        self.dial_3.setObjectName(_fromUtf8("dial_3"))
        self.gridLayout.addWidget(self.dial_3, 0, 2, 1, 1)
        self.pitch = QtGui.QLabel(self.widget1)
        self.pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.pitch.setObjectName(_fromUtf8("pitch"))
        self.gridLayout.addWidget(self.pitch, 1, 1, 1, 1)
        self.dial = QtGui.QDial(self.widget1)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.gridLayout.addWidget(self.dial, 0, 0, 1, 1)
        self.distortion = QtGui.QLabel(self.widget1)
        self.distortion.setAlignment(QtCore.Qt.AlignCenter)
        self.distortion.setObjectName(_fromUtf8("distortion"))
        self.gridLayout.addWidget(self.distortion, 1, 2, 1, 1)
        self.volume = QtGui.QLabel(self.widget1)
        self.volume.setAlignment(QtCore.Qt.AlignCenter)
        self.volume.setObjectName(_fromUtf8("volume"))
        self.gridLayout.addWidget(self.volume, 1, 0, 1, 1)
        self.dial_2 = QtGui.QDial(self.widget1)
        self.dial_2.setObjectName(_fromUtf8("dial_2"))
        self.gridLayout.addWidget(self.dial_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sintetizador de Áudio", None))
        self.frequencia.setText(_translate("MainWindow", "Frequência", None))
        self.pitch.setText(_translate("MainWindow", "Pitch", None))
        self.distortion.setText(_translate("MainWindow", "Distortion", None))
        self.volume.setText(_translate("MainWindow", "Volume", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))

from PyQt4 import Qwt5
import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

