# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Tue Nov 19 23:10:31 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(710, 609)
        MainWindow.setMaximumSize(QtCore.QSize(1443, 921))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tecla1 = QtGui.QGraphicsView(self.centralwidget)
        self.tecla1.setGeometry(QtCore.QRect(65, 251, 80, 320))
        self.tecla1.setMinimumSize(QtCore.QSize(80, 320))
        self.tecla1.setMaximumSize(QtCore.QSize(70, 320))
        self.tecla1.setObjectName(_fromUtf8("tecla1"))
        self.tecla2 = QtGui.QGraphicsView(self.centralwidget)
        self.tecla2.setGeometry(QtCore.QRect(149, 251, 80, 320))
        self.tecla2.setMinimumSize(QtCore.QSize(80, 320))
        self.tecla2.setMaximumSize(QtCore.QSize(70, 320))
        self.tecla2.setObjectName(_fromUtf8("tecla2"))
        self.tecla3 = QtGui.QGraphicsView(self.centralwidget)
        self.tecla3.setGeometry(QtCore.QRect(233, 251, 80, 320))
        self.tecla3.setMinimumSize(QtCore.QSize(80, 320))
        self.tecla3.setMaximumSize(QtCore.QSize(70, 320))
        self.tecla3.setObjectName(_fromUtf8("tecla3"))
        self.tecla4 = QtGui.QGraphicsView(self.centralwidget)
        self.tecla4.setGeometry(QtCore.QRect(317, 251, 80, 320))
        self.tecla4.setMinimumSize(QtCore.QSize(80, 320))
        self.tecla4.setMaximumSize(QtCore.QSize(70, 320))
        self.tecla4.setObjectName(_fromUtf8("tecla4"))
        self.tecla5 = QtGui.QGraphicsView(self.centralwidget)
        self.tecla5.setGeometry(QtCore.QRect(401, 251, 80, 320))
        self.tecla5.setMinimumSize(QtCore.QSize(80, 320))
        self.tecla5.setMaximumSize(QtCore.QSize(70, 320))
        self.tecla5.setObjectName(_fromUtf8("tecla5"))
        self.tecla6 = QtGui.QGraphicsView(self.centralwidget)
        self.tecla6.setGeometry(QtCore.QRect(485, 251, 80, 320))
        self.tecla6.setMinimumSize(QtCore.QSize(80, 320))
        self.tecla6.setMaximumSize(QtCore.QSize(70, 320))
        self.tecla6.setObjectName(_fromUtf8("tecla6"))
        self.tecla7 = QtGui.QGraphicsView(self.centralwidget)
        self.tecla7.setGeometry(QtCore.QRect(569, 251, 80, 320))
        self.tecla7.setMinimumSize(QtCore.QSize(80, 320))
        self.tecla7.setMaximumSize(QtCore.QSize(70, 320))
        self.tecla7.setObjectName(_fromUtf8("tecla7"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 250, 222, 202))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setSpacing(40)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tecla10 = QtGui.QGraphicsView(self.layoutWidget)
        self.tecla10.setMinimumSize(QtCore.QSize(40, 200))
        self.tecla10.setMaximumSize(QtCore.QSize(40, 200))
        self.tecla10.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.tecla10.setObjectName(_fromUtf8("tecla10"))
        self.horizontalLayout_3.addWidget(self.tecla10)
        self.tecla11 = QtGui.QGraphicsView(self.layoutWidget)
        self.tecla11.setMinimumSize(QtCore.QSize(40, 200))
        self.tecla11.setMaximumSize(QtCore.QSize(40, 200))
        self.tecla11.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.tecla11.setObjectName(_fromUtf8("tecla11"))
        self.horizontalLayout_3.addWidget(self.tecla11)
        self.tecla12 = QtGui.QGraphicsView(self.layoutWidget)
        self.tecla12.setMinimumSize(QtCore.QSize(40, 200))
        self.tecla12.setMaximumSize(QtCore.QSize(40, 200))
        self.tecla12.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.tecla12.setObjectName(_fromUtf8("tecla12"))
        self.horizontalLayout_3.addWidget(self.tecla12)
        self.graficoplot = Qwt5.QwtPlot(self.centralwidget)
        self.graficoplot.setGeometry(QtCore.QRect(280, 20, 361, 191))
        self.graficoplot.setProperty("propertiesDocument", _fromUtf8(""))
        self.graficoplot.setObjectName(_fromUtf8("graficoplot"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 250, 132, 202))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(45)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tecla8 = QtGui.QGraphicsView(self.widget)
        self.tecla8.setMinimumSize(QtCore.QSize(40, 200))
        self.tecla8.setMaximumSize(QtCore.QSize(40, 200))
        self.tecla8.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.tecla8.setObjectName(_fromUtf8("tecla8"))
        self.horizontalLayout_2.addWidget(self.tecla8)
        self.tecla9 = QtGui.QGraphicsView(self.widget)
        self.tecla9.setMinimumSize(QtCore.QSize(40, 200))
        self.tecla9.setMaximumSize(QtCore.QSize(40, 200))
        self.tecla9.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.tecla9.setObjectName(_fromUtf8("tecla9"))
        self.horizontalLayout_2.addWidget(self.tecla9)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(70, 110, 181, 101))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dial_3 = QtGui.QDial(self.widget1)
        self.dial_3.setObjectName(_fromUtf8("dial_3"))
        self.gridLayout.addWidget(self.dial_3, 0, 2, 1, 1)
        self.pitch = QtGui.QLabel(self.widget1)
        self.pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.pitch.setObjectName(_fromUtf8("pitch"))
        self.gridLayout.addWidget(self.pitch, 1, 1, 1, 1)
        self.dial = QtGui.QDial(self.widget1)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.gridLayout.addWidget(self.dial, 0, 0, 1, 1)
        self.distortion = QtGui.QLabel(self.widget1)
        self.distortion.setAlignment(QtCore.Qt.AlignCenter)
        self.distortion.setObjectName(_fromUtf8("distortion"))
        self.gridLayout.addWidget(self.distortion, 1, 2, 1, 1)
        self.volume = QtGui.QLabel(self.widget1)
        self.volume.setAlignment(QtCore.Qt.AlignCenter)
        self.volume.setObjectName(_fromUtf8("volume"))
        self.gridLayout.addWidget(self.volume, 1, 0, 1, 1)
        self.dial_2 = QtGui.QDial(self.widget1)
        self.dial_2.setObjectName(_fromUtf8("dial_2"))
        self.gridLayout.addWidget(self.dial_2, 0, 1, 1, 1)
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(70, 10, 181, 91))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lcdFrequencia = QtGui.QLCDNumber(self.widget2)
        self.lcdFrequencia.setObjectName(_fromUtf8("lcdFrequencia"))
        self.verticalLayout.addWidget(self.lcdFrequencia)
        self.frequencia = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.frequencia.setFont(font)
        self.frequencia.setAlignment(QtCore.Qt.AlignCenter)
        self.frequencia.setObjectName(_fromUtf8("frequencia"))
        self.verticalLayout.addWidget(self.frequencia)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sintetizador de Áudio", None))
        self.pitch.setText(_translate("MainWindow", "Pitch", None))
        self.distortion.setText(_translate("MainWindow", "Distortion", None))
        self.volume.setText(_translate("MainWindow", "Volume", None))
        self.frequencia.setText(_translate("MainWindow", "Frequência", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))

from PyQt4 import Qwt5


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

